name: Source

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      shell: bash
      run: echo "${{ github.event_name }} ${{ github.ref }}"
    - uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: refs/heads/master
        check-name: 'Target'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
        allowed-conclusions: success
    - name: test
      shell: bash
      run: echo "done"

